$t = Get-ScheduledTask -TaskName "AmazonMonitor-Batch1"
$info = Get-ScheduledTaskInfo -TaskName "AmazonMonitor-Batch1"
Write-Host "Task: $($t.TaskName)"
Write-Host "State: $($t.State)"
Write-Host "LastRun: $($info.LastRunTime)"
Write-Host "NextRun: $($info.NextRunTime)"
Write-Host "Result: $($info.LastTaskResult)"
Write-Host ""
Write-Host "Principal: User=$($t.Principal.UserId), Logon=$($t.Principal.LogonType), RunLevel=$($t.Principal.RunLevel)"
Write-Host ""
$s = $t.Settings
Write-Host "AllowDemandStart: $($s.AllowDemandStart)"
Write-Host "StartWhenAvailable: $($s.StartWhenAvailable)"
Write-Host "DisallowStartIfOnBatteries: $($s.DisallowStartIfOnBatteries)"
Write-Host "StopIfGoingOnBatteries: $($s.StopIfGoingOnBatteries)"
Write-Host "ExecutionTimeLimit: $($s.ExecutionTimeLimit)"
Write-Host "MultipleInstances: $($s.MultipleInstances)"
Write-Host ""
$trig = $t.Triggers[0]
Write-Host "Trigger StartBoundary: $($trig.StartBoundary)"
Write-Host "Trigger Enabled: $($trig.Enabled)"
